### ISSUE TITLE
Ajouts possibles sur `DetailsPage`

### ISSUE THREAD

**Issue by aurelienLavanchy** [MichaelLELU/Pokedex-TS#33]
- [x] Un bouton pour revenir en arrière (du style `window.history.back`)
- [x] Des boutons de navigation pour changer l'id (+1/-1) sans avoir à toucher à l'URL ou revenir en arrière pour sélectionner une autre entrée

**Comment by MichaelLELU** [comment]
Bien vue et pourquoi pas tester de designer la page pokemon details avec un style de pokedex sa peut etre  simpats a designer sur figma https://www.pixiz.com/frame/Pokedex-2200032
